#!/usr/bin/env perl

use 5.014;
use warnings;
use lib 'lib';

use App::Commando;

use WebService::Questhub::Quest;
use WebService::Questhub::Realm;
use WebService::Questhub::Realms;

my $p = App::Commando::program('qh');
$p->version('0.000001');

my $realms = $p->command('realms');
$realms->action(sub {
    my ($argv, $config) = @_;

    my $wq_result = WebService::Questhub::Realms->new->list;
    while ( my $item = $wq_result->get_next ) {
        say $item->id;
    }
});

my $realm = $p->command('realm');
$realm->option('id', 'id=s');
$realm->action(sub {
    my ($argv, $config) = @_;

    my $arg = $argv->[0];

    if ( $arg && $arg eq 'quests' ) {
        say "realm's quests stub";
    }
    else {
        my $reaml = WebService::Questhub::Realm->new->get(id => $config->{id});
        say $reaml->description;
    }
});

my $quests = $p->command('quests');
$quests->option('player', 'player=s');
$quests->option('self', '--self');
$quests->action(sub {
    my ($argv, $config) = @_;

    if ( $config->{player} ) {
        say "player's quests stub";
    }
    elsif ( $config->{self} ) {
        say "my quests stub"
    }
});

my $quest = $p->command('quest');
$quest->option('id', 'id=s');
$quest->option('title', 'title=s');
$quest->action(sub {
    my ($argv, $config) = @_;

    my $arg = $argv->[0];

    unless ( $arg ) {
        say "quest info stub";
    }
    else {
        my $q = WebService::Questhub::Quest->new->request(
            action => $arg,
            %$config,
        );
        say $q->{_id};
    }
});

$p->go;
